package com.cisco.la.mapper;

import com.cisco.la.model.CourseModel;
import com.cisco.la.model.CourseModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    long countByExample(CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int deleteByExample(CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int insert(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int insertSelective(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    List<CourseModel> selectByExample(CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    CourseModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") CourseModel record, @Param("example") CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByExample(@Param("record") CourseModel record, @Param("example") CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByPrimaryKeySelective(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_course
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByPrimaryKey(CourseModel record);
}