package com.cisco.la.mapper;

import com.cisco.la.model.CourseHistoryModel;
import com.cisco.la.model.CourseHistoryModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseHistoryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_crs_history
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    long countByExample(CourseHistoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_crs_history
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int deleteByExample(CourseHistoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_crs_history
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int insert(CourseHistoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_crs_history
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int insertSelective(CourseHistoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_crs_history
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    List<CourseHistoryModel> selectByExample(CourseHistoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_crs_history
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") CourseHistoryModel record, @Param("example") CourseHistoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_crs_history
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByExample(@Param("record") CourseHistoryModel record, @Param("example") CourseHistoryModelExample example);
}