package com.cisco.la.mapper;

import com.cisco.la.model.GoldenSampleModel;
import com.cisco.la.model.GoldenSampleModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoldenSampleModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    long countByExample(GoldenSampleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int deleteByExample(GoldenSampleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int insert(GoldenSampleModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int insertSelective(GoldenSampleModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    List<GoldenSampleModel> selectByExample(GoldenSampleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") GoldenSampleModel record, @Param("example") GoldenSampleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    int updateByExample(@Param("record") GoldenSampleModel record, @Param("example") GoldenSampleModelExample example);
}