package com.cisco.la.model;

import java.util.Date;

public class CourseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_course.crs_id
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_course.crs_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_course.crs_price
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_course.crs_startdate
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_course.crs_enddate
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_course.crs_active
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private Boolean active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_course.crs_id
     *
     * @return the value of public.la_course.crs_id
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_course.crs_id
     *
     * @param id the value for public.la_course.crs_id
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_course.crs_name
     *
     * @return the value of public.la_course.crs_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_course.crs_name
     *
     * @param name the value for public.la_course.crs_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_course.crs_price
     *
     * @return the value of public.la_course.crs_price
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_course.crs_price
     *
     * @param price the value for public.la_course.crs_price
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_course.crs_startdate
     *
     * @return the value of public.la_course.crs_startdate
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_course.crs_startdate
     *
     * @param startDate the value for public.la_course.crs_startdate
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_course.crs_enddate
     *
     * @return the value of public.la_course.crs_enddate
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_course.crs_enddate
     *
     * @param endDate the value for public.la_course.crs_enddate
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_course.crs_active
     *
     * @return the value of public.la_course.crs_active
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_course.crs_active
     *
     * @param active the value for public.la_course.crs_active
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setActive(Boolean active) {
        this.active = active;
    }
}