package com.cisco.la.model;

import java.util.Date;

public class GoldenSampleModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_golden_sample.smpl_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_golden_sample.smpl_role
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_golden_sample.smpl_rl_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_golden_sample.smpl_mandatory
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private String mandatory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_golden_sample.smpl_optional
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private String optional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_golden_sample.smpl_update_time
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_golden_sample.smpl_active
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    private Boolean active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_golden_sample.smpl_name
     *
     * @return the value of public.la_golden_sample.smpl_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_golden_sample.smpl_name
     *
     * @param name the value for public.la_golden_sample.smpl_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_golden_sample.smpl_role
     *
     * @return the value of public.la_golden_sample.smpl_role
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_golden_sample.smpl_role
     *
     * @param role the value for public.la_golden_sample.smpl_role
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_golden_sample.smpl_rl_name
     *
     * @return the value of public.la_golden_sample.smpl_rl_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_golden_sample.smpl_rl_name
     *
     * @param roleName the value for public.la_golden_sample.smpl_rl_name
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_golden_sample.smpl_mandatory
     *
     * @return the value of public.la_golden_sample.smpl_mandatory
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public String getMandatory() {
        return mandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_golden_sample.smpl_mandatory
     *
     * @param mandatory the value for public.la_golden_sample.smpl_mandatory
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setMandatory(String mandatory) {
        this.mandatory = mandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_golden_sample.smpl_optional
     *
     * @return the value of public.la_golden_sample.smpl_optional
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public String getOptional() {
        return optional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_golden_sample.smpl_optional
     *
     * @param optional the value for public.la_golden_sample.smpl_optional
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setOptional(String optional) {
        this.optional = optional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_golden_sample.smpl_update_time
     *
     * @return the value of public.la_golden_sample.smpl_update_time
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_golden_sample.smpl_update_time
     *
     * @param updateTime the value for public.la_golden_sample.smpl_update_time
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_golden_sample.smpl_active
     *
     * @return the value of public.la_golden_sample.smpl_active
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_golden_sample.smpl_active
     *
     * @param active the value for public.la_golden_sample.smpl_active
     *
     * @mbg.generated Fri Dec 29 14:00:32 CST 2017
     */
    public void setActive(Boolean active) {
        this.active = active;
    }
}